In [2]:
import pandas as pd
df = pd.read_csv("raw_data.csv")

In [15]:
df["gender"].str.upper()
df["gender"].str.lower()
df["gender"].str.capitalize()
df["country"].str.contains("india", case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [37]:
df2 = df
# apply()
df2["Tax"] = df2["income"] .apply(lambda x: "20%" if x > 60000 else "10%")

# map() 
gen_map = {"Male": "M" , "Female" : "F" , "Unknown" : "U"}
df2["gender"] = df["gender"].map(gen_map)
# assign()
# df2["new_income"] = df2["income"]*1.1)
df2 = df2.assign(new_20 = df2["income"]*1.2)
df2["country"] = df2["country"].replace("USA", "US")
df2

    id          name   age country gender   income  Tax  new_income   new_20
0    1      John Doe  29.0      US    NaN  55000.0  10%     60500.0  66000.0
1    1      John Doe  29.0      US    NaN  55000.0  10%     60500.0  66000.0
2    2    Jane Smith   NaN  Canada    NaN  62000.0  20%     68200.0  74400.0
3    3          Alex   NaN      US    NaN  47000.0  10%     51700.0  56400.0
4    4  Maria Garcia  34.0   Spain    NaN      NaN  10%         NaN      NaN
5    5        Li Wei  27.0   China    NaN  51000.0  10%     56100.0  61200.0
6    6           NaN  45.0   India    NaN  73000.0  20%     80300.0  87600.0
7    7    Ahmed Khan  38.0     NaN    NaN  68000.0  20%     74800.0  81600.0
8    8    Rachel Lee  29.0      US    NaN  62000.0  20%     68200.0  74400.0
9    9   Carlos Ruiz   NaN  Mexico    NaN  45000.0  10%     49500.0  54000.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0  69600.0

In [3]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0